version: '3'

services:
  nestjs:
    container_name: api_nestjs
    build:
      context: "./nestjs"
    expose:
      - "3000"
    volumes:
      - ../api:/opt/api
    ports:
      - "5000:3000"
    depends_on:
      - redis
    networks:
      default:
        aliases:
          - api_nestjs
    entrypoint: yarn start:dev

  redis:
    image: redis:6.0-alpine
    container_name: app_redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: "bridge"