version: '3'

services:
  nestjs:
    container_name: api_nestjs
    build:
      context: "./nestjs"
    expose:
      - "3000"
    volumes:
      - ../api:/opt/api
    ports:
      - "5000:3000"
    depends_on:
      - db_postgres
      - redis
    networks:
      default:
        aliases:
          - api_nestjs
    entrypoint: yarn start:dev

  redis:
    image: redis:6.0-alpine
    container_name: app_redis
    ports:
      - "6379:6379"

  db_postgres:
    image: postgres:12-alpine
    container_name: api_postgres
    expose:
      - "5432"
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD=change_me
      - POSTGRES_USER=nestjs
      - POSTGRES_DB=queue_nestjs

volumes: 
  postgres-data: